#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Sync new_products_data.js from dashboard.dmdmnow.com and notify Lasfit floor-mat
new arrivals to the Feishu group.

Notification rule (fixed by owner, do NOT change):
  b == "Lasfit" AND title contains "Floor Mat" / "Cargo Mat" / "Bed Mat"
  AND d == today (Asia/Shanghai). Peripheral accessories are excluded by the
  keyword list itself.

Card format replicates the existing group card 1:1:
  title: 🆕 Lasfit 新品上架
  line1: 📅 <date> | Lasfit 新品
  line2: 🚗 脚垫类新品 (N) + one link line per product ($price | date)
  hr + empty note
"""
import json
import os
import sys
import time
import urllib.request
import urllib.error
from datetime import datetime, timedelta, timezone

CST = timezone(timedelta(hours=8))  # Asia/Shanghai, fixed offset (no DST)

DATA_URL = os.environ.get("DASHBOARD_DATA_URL", "https://dashboard.dmdmnow.com/new_products_data.js")
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(REPO_ROOT, "new_products_data.js")
STATE_FILE = os.path.join(REPO_ROOT, "state", "notified_ids.json")

MAT_KEYWORDS = ("floor mat", "cargo mat", "bed mat")
STATE_KEEP_DAYS = 30


def http_get(url, timeout=30, retries=2):
    last_err = None
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (dmdmnow-dashboard-sync)"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return r.read().decode("utf-8", errors="replace")
        except (urllib.error.URLError, TimeoutError) as e:
            last_err = e
            if attempt < retries:
                time.sleep(3)
    raise RuntimeError(f"fetch failed after {retries + 1} attempts: {last_err}")


def http_post_json(url, payload, headers=None, timeout=20):
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json", **(headers or {})})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode("utf-8"))


def parse_items(text):
    """Extract the JSON array from `var NEW_PRODUCTS = [...]`."""
    start, end = text.index("["), text.rindex("]") + 1
    return json.loads(text[start:end])


def load_local_items():
    if not os.path.exists(DATA_FILE):
        return None
    try:
        return parse_items(open(DATA_FILE, encoding="utf-8").read())
    except Exception:
        return None


def write_data_file(items):
    body = json.dumps(items, ensure_ascii=False, indent=1)
    content = (
        "// Auto-generated by dmdmnow-dashboard GitHub Actions sync\n"
        "// Source: dashboard.dmdmnow.com/new_products_data.js\n"
        "var NEW_PRODUCTS = " + body + "\n"
    )
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        f.write(content)


def item_id(p):
    return f"{p.get('u', '')}::{p.get('t', '')}"


def is_lasfit_mat(p):
    if p.get("b") != "Lasfit":
        return False
    t = (p.get("t") or "").lower()
    return any(kw in t for kw in MAT_KEYWORDS)


def load_state():
    if os.path.exists(STATE_FILE):
        try:
            return json.load(open(STATE_FILE, encoding="utf-8"))
        except Exception:
            pass
    return {}


def save_state(state):
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=1, sort_keys=True)
        f.write("\n")


def purge_state(state, today):
    cutoff = (today - timedelta(days=STATE_KEEP_DAYS)).strftime("%Y-%m-%d")
    return {k: v for k, v in state.items() if v >= cutoff}


def build_card(hits, day):
    """Replicate the exact legacy card structure used in the group today."""
    line2 = [{"tag": "text", "text": f"🚗 脚垫类新品 ({len(hits)})"}]
    for i, p in enumerate(hits):
        price = p.get("p")
        price_str = f"${price:.2f}" if isinstance(price, (int, float)) else ""
        sep = "\n• " if i < len(hits) - 1 else ""
        line2.append({"tag": "text", "text": "\n• "})
        line2.append({"tag": "a", "href": p.get("u", ""), "text": p.get("t", "")})
        line2.append({"tag": "text", "text": f"  {price_str}  | {p.get('d', '')}{sep}"})
    card = {
        "title": "🆕 Lasfit 新品上架",
        "elements": [
            [{"tag": "text", "text": f"📅 {day} | Lasfit 新品"}],
            line2,
            [{"tag": "hr"}],
            [{"tag": "note", "elements": []}],
        ],
    }
    return card


def feishu_token(app_id, app_secret):
    resp = http_post_json(
        "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal",
        {"app_id": app_id, "app_secret": app_secret},
    )
    if resp.get("code") != 0 or not resp.get("tenant_access_token"):
        raise RuntimeError(f"tenant token failed: {resp}")
    return resp["tenant_access_token"]


def send_card(token, chat_id, card):
    resp = http_post_json(
        "https://open.feishu.cn/open-apis/im/v1/messages?receive_id_type=chat_id",
        {"receive_id": chat_id, "msg_type": "interactive", "content": json.dumps(card, ensure_ascii=False)},
        headers={"Authorization": f"Bearer {token}"},
    )
    if resp.get("code") != 0:
        raise RuntimeError(f"send message failed: {resp}")
    return resp


def main():
    dry_run = os.environ.get("INPUT_DRY_RUN", "").lower() == "true"
    target_date = os.environ.get("INPUT_TARGET_DATE", "").strip()
    today = datetime.now(CST)
    day = target_date or today.strftime("%Y-%m-%d")

    print(f"[sync] fetching {DATA_URL}")
    upstream_items = parse_items(http_get(DATA_URL))
    print(f"[sync] upstream items: {len(upstream_items)}")

    local_items = load_local_items()
    if local_items != upstream_items:
        write_data_file(upstream_items)
        print(f"[sync] new_products_data.js updated ({(local_items or []) and len(local_items) or 0} -> {len(upstream_items)} items)")
    else:
        print("[sync] data unchanged")

    state = load_state()
    purged = purge_state(state, today)
    state_changed = len(purged) != len(state)
    state = purged

    hits = [p for p in upstream_items if p.get("d") == day and is_lasfit_mat(p) and item_id(p) not in state]
    hits.sort(key=lambda p: p.get("t", ""))
    print(f"[notify] date={day} new Lasfit mat items: {len(hits)}")

    if hits:
        card = build_card(hits, day)
        if dry_run:
            print("[notify] DRY RUN, card would be:")
            print(json.dumps(card, ensure_ascii=False, indent=1))
        else:
            app_id = os.environ["FEISHU_APP_ID"]
            app_secret = os.environ["FEISHU_APP_SECRET"]
            chat_id = os.environ["FEISHU_CHAT_ID"]
            token = feishu_token(app_id, app_secret)
            send_card(token, chat_id, card)
            print(f"[notify] card sent with {len(hits)} item(s)")
            for p in hits:
                state[item_id(p)] = day
            state_changed = True

    if state_changed:
        save_state(state)
        print("[state] notified_ids.json updated")
    else:
        print("[state] unchanged")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)
